set sql_safe_updates=0;
UPDATE asin
JOIN brand_scrapped ON brand_scrapped.name = asin.brand_scrapped
SET asin.brand_scrapped_id = brand_scrapped.brand_id
WHERE asin.brand_scrapped_id IS NULL;

update asin set brand_id=346 where lower(left(title,8))='zorestar';
update asin set brand_id=93 where lower(left(title,6))='zodaca';
update asin set brand_id=215 where lower(left(title,7))='zap it!';
update asin set brand_id=450 where lower(left(title,4))='zaos';
update asin set brand_id=304 where lower(left(title,6))='yumaya';
update asin set brand_id=461 where lower(left(title,6))='yoyork';
update asin set brand_id=80 where lower(left(title,13))='yankee candle';
update asin set brand_id=443 where lower(left(title,9))='wow! pods';
update asin set brand_id=146 where lower(left(title,9))='wood grip';
update asin set brand_id=41 where lower(left(title,10))='wod nation';
update asin set brand_id=347 where lower(left(title,15))='winning fingers';
update asin set brand_id=444 where lower(left(title,7))='windsor';
update asin set brand_id=99 where lower(left(title,13))='window garden';
update asin set brand_id=397 where lower(left(title,13))='wildtier herz';
update asin set brand_id=406 where lower(left(title,15))='wildlife friend';
update asin set brand_id=225 where lower(left(title,20))='wild wolf outfitters';
update asin set brand_id=108 where lower(left(title,25))='wholesale plumbing supply';
update asin set brand_id=316 where lower(left(title,16))='whole housewares';
update asin set brand_id=119 where lower(left(title,12))='whizzy wheel';
update asin set brand_id=470 where lower(left(title,10))='white coat';
update asin set brand_id=514 where lower(left(title,9))='wellbrite';
update asin set brand_id=339 where lower(left(title,7))='watergo';
update asin set brand_id=455 where lower(left(title,6))='vp tek';
update asin set brand_id=357 where lower(left(title,7))='vp home';
update asin set brand_id=220 where lower(left(title,9))='vorfreude';
update asin set brand_id=456 where lower(left(title,7))='voltada';
update asin set brand_id=513 where lower(left(title,13))='vine homecare';
update asin set brand_id=274 where lower(left(title,8))='viirkuja';
update asin set brand_id=270 where lower(left(title,9))='vibo care';
update asin set brand_id=428 where lower(left(title,17))='verymerrymakering';
update asin set brand_id=117 where lower(left(title,6))='vdomus';
update asin set brand_id=386 where lower(left(title,11))='value grubs';
update asin set brand_id=512 where lower(left(title,4))='vaci';
update asin set brand_id=143 where lower(left(title,5))='uulki';
update asin set brand_id=289 where lower(left(title,12))='urbanfit pro';
update asin set brand_id=440 where lower(left(title,10))='urban tech';
update asin set brand_id=390 where lower(left(title,12))='urban design';
update asin set brand_id=287 where lower(left(title,11))='upper order';
update asin set brand_id=21 where lower(left(title,11))='untamed sox';
update asin set brand_id=511 where lower(left(title,6))='unokki';
update asin set brand_id=449 where lower(left(title,9))='unbekannt';
update asin set brand_id=258 where lower(left(title,10))='tunephonik';
update asin set brand_id=137 where lower(left(title,18))='truremedy naturals';
update asin set brand_id=436 where lower(left(title,9))='tribe wod';
update asin set brand_id=196 where lower(left(title,8))='tresalto';
update asin set brand_id=510 where lower(left(title,10))='travelwell';
update asin set brand_id=199 where lower(left(title,8))='travelax';
update asin set brand_id=439 where lower(left(title,12))='travel elite';
update asin set brand_id=256 where lower(left(title,14))='tranquilbeauty';
update asin set brand_id=473 where lower(left(title,9))='trainmate';
update asin set brand_id=145 where lower(left(title,8))='top race';
update asin set brand_id=221 where lower(left(title,9))='toolzilla';
update asin set brand_id=90 where lower(left(title,8))='toodaloo';
update asin set brand_id=203 where lower(left(title,17))='tobe readyforlife';
update asin set brand_id=55 where lower(left(title,13))='tickle & main';
update asin set brand_id=408 where lower(left(title,8))='thingles';
update asin set brand_id=388 where lower(left(title,8))='the shop';
update asin set brand_id=306 where lower(left(title,11))='the gym keg';
update asin set brand_id=15 where lower(left(title,21))='the gifted stationery';
update asin set brand_id=63 where lower(left(title,20))='the cocktail box co.';
update asin set brand_id=367 where lower(left(title,21))='the battery organizer';
update asin set brand_id=65 where lower(left(title,13))='tf publishing';
update asin set brand_id=181 where lower(left(title,10))='telefunken';
update asin set brand_id=391 where lower(left(title,7))='tastory';
update asin set brand_id=509 where lower(left(title,8))='tapeplus';
update asin set brand_id=370 where lower(left(title,36))='tame the wild make your beard behave';
update asin set brand_id=30 where lower(left(title,16))='talented kitchen';
update asin set brand_id=17 where lower(left(title,8))='tadpoles';
update asin set brand_id=422 where lower(left(title,5))='sølmo';
update asin set brand_id=432 where lower(left(title,8))='swoopies';
update asin set brand_id=380 where lower(left(title,14))='swiss outdoors';
update asin set brand_id=508 where lower(left(title,16))='sweet vibrations';
update asin set brand_id=283 where lower(left(title,11))='sweet vibes';
update asin set brand_id=353 where lower(left(title,12))='sweet ponies';
update asin set brand_id=92 where lower(left(title,21))='sustainable greetings';
update asin set brand_id=81 where lower(left(title,8))='supplift';
update asin set brand_id=207 where lower(left(title,7))='sunglow';
update asin set brand_id=381 where lower(left(title,10))='summit one';
update asin set brand_id=28 where lower(left(title,14))='strictly briks';
update asin set brand_id=105 where lower(left(title,9))='stravilio';
update asin set brand_id=5 where lower(left(title,14))='stockroom plus';
update asin set brand_id=109 where lower(left(title,9))='stepngrip';
update asin set brand_id=216 where lower(left(title,12))='steadydoggie';
update asin set brand_id=59 where lower(left(title,5))='stead';
update asin set brand_id=399 where lower(left(title,22))='starbright grill light';
update asin set brand_id=170 where lower(left(title,10))='star right';
update asin set brand_id=361 where lower(left(title,13))='squeeze craft';
update asin set brand_id=413 where lower(left(title,10))='sportanics';
update asin set brand_id=507 where lower(left(title,14))='spooky central';
update asin set brand_id=371 where lower(left(title,8))='spaßwerk';
update asin set brand_id=10 where lower(left(title,16))='sparkle and bash';
update asin set brand_id=150 where lower(left(title,10))='spacesaver';
update asin set brand_id=180 where lower(left(title,9))='space max';
update asin set brand_id=18 where lower(left(title,5))='soxxo';
update asin set brand_id=303 where lower(left(title,12))='sousvide art';
update asin set brand_id=73 where lower(left(title,4))='sony';
update asin set brand_id=326 where lower(left(title,6))='somera';
update asin set brand_id=329 where lower(left(title,9))='sofamatch';
update asin set brand_id=267 where lower(left(title,8))='socialic';
update asin set brand_id=442 where lower(left(title,13))='snug a babies';
update asin set brand_id=110 where lower(left(title,8))='smartweb';
update asin set brand_id=272 where lower(left(title,9))='smartpeas';
update asin set brand_id=330 where lower(left(title,25))='slokey discover the world';
update asin set brand_id=174 where lower(left(title,10))='sliptogrip';
update asin set brand_id=485 where lower(left(title,12))='slight touch';
update asin set brand_id=227 where lower(left(title,9))='sleepingo';
update asin set brand_id=506 where lower(left(title,17))='sleeping partners';
update asin set brand_id=279 where lower(left(title,16))='sir marlon grant';
update asin set brand_id=505 where lower(left(title,13))='simply genius';
update asin set brand_id=320 where lower(left(title,6))='silvon';
update asin set brand_id=167 where lower(left(title,15))='signs authority';
update asin set brand_id=417 where lower(left(title,16))='signature living';
update asin set brand_id=214 where lower(left(title,16))='signature garden';
update asin set brand_id=472 where lower(left(title,15))='shirt stay plus';
update asin set brand_id=423 where lower(left(title,16))='serene evolution';
update asin set brand_id=213 where lower(left(title,5))='schon';
update asin set brand_id=360 where lower(left(title,8))='schoberg';
update asin set brand_id=106 where lower(left(title,6))='sauder';
update asin set brand_id=169 where lower(left(title,6))='satina';
update asin set brand_id=412 where lower(left(title,9))='saniverde';
update asin set brand_id=504 where lower(left(title,9))='sameriver';
update asin set brand_id=311 where lower(left(title,9))='safestrap';
update asin set brand_id=420 where lower(left(title,5))='s-mag';
update asin set brand_id=240 where lower(left(title,5))='ryher';
update asin set brand_id=43 where lower(left(title,13))='running buddy';
update asin set brand_id=19 where lower(left(title,11))='rose cheeks';
update asin set brand_id=96 where lower(left(title,17))='room/dividers/now';
update asin set brand_id=23 where lower(left(title,6))='ri pac';
update asin set brand_id=315 where lower(left(title,17))='regal trunk & co.';
update asin set brand_id=56 where lower(left(title,16))='real good coffee';
update asin set brand_id=477 where lower(left(title,9))='readerest';
update asin set brand_id=358 where lower(left(title,7))='rawbond';
update asin set brand_id=445 where lower(left(title,4))='raia';
update asin set brand_id=71 where lower(left(title,7))='radiate';
update asin set brand_id=231 where lower(left(title,14))='quality contor';
update asin set brand_id=291 where lower(left(title,6))='purava';
update asin set brand_id=179 where lower(left(title,17))='prosumer''s choice';
update asin set brand_id=469 where lower(left(title,8))='prosteam';
update asin set brand_id=415 where lower(left(title,13))='prosper honey';
update asin set brand_id=160 where lower(left(title,7))='prodive';
update asin set brand_id=88 where lower(left(title,8))='prodepot';
update asin set brand_id=273 where lower(left(title,8))='prodarts';
update asin set brand_id=151 where lower(left(title,14))='pro bike tools';
update asin set brand_id=464 where lower(left(title,8))='prexware';
update asin set brand_id=101 where lower(left(title,7))='prextex';
update asin set brand_id=284 where lower(left(title,12))='pretty kitty';
update asin set brand_id=98 where lower(left(title,7))='prestee';
update asin set brand_id=359 where lower(left(title,12))='present mind';
update asin set brand_id=206 where lower(left(title,24))='precision quilting tools';
update asin set brand_id=104 where lower(left(title,5))='powrx';
update asin set brand_id=31 where lower(left(title,17))='powerstone pumice';
update asin set brand_id=290 where lower(left(title,8))='poweroni';
update asin set brand_id=336 where lower(left(title,10))='power pins';
update asin set brand_id=144 where lower(left(title,11))='power & co.';
update asin set brand_id=246 where lower(left(title,9))='portovino';
update asin set brand_id=237 where lower(left(title,5))='popco';
update asin set brand_id=302 where lower(left(title,7))='plemont';
update asin set brand_id=465 where lower(left(title,8))='playmind';
update asin set brand_id=177 where lower(left(title,10))='pixiecrush';
update asin set brand_id=503 where lower(left(title,12))='pipilo press';
update asin set brand_id=148 where lower(left(title,15))='pine tree tools';
update asin set brand_id=334 where lower(left(title,11))='pfotenolymp';
update asin set brand_id=292 where lower(left(title,9))='pet union';
update asin set brand_id=66 where lower(left(title,16))='pet prep academy';
update asin set brand_id=318 where lower(left(title,6))='pesani';
update asin set brand_id=202 where lower(left(title,20))='penguin art supplies';
update asin set brand_id=460 where lower(left(title,9))='pee buddy';
update asin set brand_id=85 where lower(left(title,14))='pebble & crane';
update asin set brand_id=373 where lower(left(title,11))='pardo cigar';
update asin set brand_id=1 where lower(left(title,12))='paper junkie';
update asin set brand_id=263 where lower(left(title,10))='paint mark';
update asin set brand_id=375 where lower(left(title,8))='owngrown';
update asin set brand_id=404 where lower(left(title,9))='overgrill';
update asin set brand_id=419 where lower(left(title,7))='outlery';
update asin set brand_id=271 where lower(left(title,13))='outdoor panda';
update asin set brand_id=321 where lower(left(title,5))='osaka';
update asin set brand_id=44 where lower(left(title,19))='original stationery';
update asin set brand_id=341 where lower(left(title,8))='oraganix';
update asin set brand_id=127 where lower(left(title,15))='open seed vault';
update asin set brand_id=245 where lower(left(title,9))='old nobby';
update asin set brand_id=94 where lower(left(title,13))='okuna outpost';
update asin set brand_id=356 where lower(left(title,17))='officeworld range';
update asin set brand_id=328 where lower(left(title,10))='officeline';
update asin set brand_id=502 where lower(left(title,6))='octago';
update asin set brand_id=382 where lower(left(title,7))='nutrani';
update asin set brand_id=60 where lower(left(title,17))='nurse and nourish';
update asin set brand_id=410 where lower(left(title,10))='novastreet';
update asin set brand_id=189 where lower(left(title,20))='nourished essentials';
update asin set brand_id=122 where lower(left(title,15))='not razor owned';
update asin set brand_id=116 where lower(left(title,9))='noa store';
update asin set brand_id=187 where lower(left(title,4))='nezt';
update asin set brand_id=242 where lower(left(title,10))='neomagnova';
update asin set brand_id=218 where lower(left(title,7))='neliblu';
update asin set brand_id=429 where lower(left(title,13))='naturschmiede';
update asin set brand_id=219 where lower(left(title,20))='national electronics';
update asin set brand_id=211 where lower(left(title,3))='nan';
update asin set brand_id=482 where lower(left(title,3))='n/a';
update asin set brand_id=168 where lower(left(title,18))='my cinema lightbox';
update asin set brand_id=437 where lower(left(title,8))='mr. pets';
update asin set brand_id=86 where lower(left(title,29))='mountain mike''s reproductions';
update asin set brand_id=97 where lower(left(title,17))='mountain grillers';
update asin set brand_id=234 where lower(left(title,17))='modern industrial';
update asin set brand_id=400 where lower(left(title,7))='mode 33';
update asin set brand_id=426 where lower(left(title,5))='mizar';
update asin set brand_id=115 where lower(left(title,8))='mister m';
update asin set brand_id=501 where lower(left(title,18))='mission automotive';
update asin set brand_id=349 where lower(left(title,12))='mighty bliss';
update asin set brand_id=49 where lower(left(title,5))='merka';
update asin set brand_id=411 where lower(left(title,10))='meistergut';
update asin set brand_id=475 where lower(left(title,7))='medikit';
update asin set brand_id=296 where lower(left(title,10))='meant2tobe';
update asin set brand_id=416 where lower(left(title,13))='matilda & co.';
update asin set brand_id=369 where lower(left(title,13))='master maison';
update asin set brand_id=327 where lower(left(title,5))='masho';
update asin set brand_id=257 where lower(left(title,9))='markenlos';
update asin set brand_id=58 where lower(left(title,13))='marble genius';
update asin set brand_id=9 where lower(left(title,10))='maplefield';
update asin set brand_id=301 where lower(left(title,5))='mango';
update asin set brand_id=282 where lower(left(title,8))='makimaja';
update asin set brand_id=57 where lower(left(title,15))='magnificent 101';
update asin set brand_id=64 where lower(left(title,7))='magneto';
update asin set brand_id=478 where lower(left(title,12))='magnet build';
update asin set brand_id=481 where lower(left(title,15))='magic sleepsuit';
update asin set brand_id=132 where lower(left(title,14))='madison supply';

update asin set brand_id=479 where lower(left(title,7))='luminrg';
update asin set brand_id=154 where lower(left(title,6))='lumare';
update asin set brand_id=155 where lower(left(title,10))='long gamma';
update asin set brand_id=186 where lower(left(title,11))='lock cowboy';
update asin set brand_id=434 where lower(left(title,7))='livonir';
update asin set brand_id=223 where lower(left(title,6))='livaia';
update asin set brand_id=398 where lower(left(title,16))='little moonshine';
update asin set brand_id=253 where lower(left(title,12))='litti pritti';
update asin set brand_id=446 where lower(left(title,10))='litti city';

update asin set brand_id=33 where lower(left(title,10))='lilgadgets';
update asin set brand_id=452 where lower(left(title,5))='liivo';
update asin set brand_id=364 where lower(left(title,12))='light autumn';
update asin set brand_id=46 where lower(left(title,11))='life mounts';
update asin set brand_id=389 where lower(left(title,10))='liebspecht';
update asin set brand_id=447 where lower(left(title,6))='libken';
update asin set brand_id=323 where lower(left(title,8))='li''l-gen';
update asin set brand_id=126 where lower(left(title,6))='lennox';
update asin set brand_id=13 where lower(left(title,7))='le juvo';
update asin set brand_id=401 where lower(left(title,11))='laxe handle';
update asin set brand_id=285 where lower(left(title,7))='lavodia';
update asin set brand_id=466 where lower(left(title,7))='lavault';
update asin set brand_id=393 where lower(left(title,10))='lava sport';
update asin set brand_id=61 where lower(left(title,8))='lascoota';
update asin set brand_id=243 where lower(left(title,5))='laevo';
update asin set brand_id=486 where lower(left(title,28))='l&amp;g london uniforms u.k.';
update asin set brand_id=200 where lower(left(title,6))='knitiq';
update asin set brand_id=351 where lower(left(title,8))='kitchtic';
update asin set brand_id=462 where lower(left(title,11))='kitchenzone';
update asin set brand_id=176 where lower(left(title,13))='kitchen gizmo';
update asin set brand_id=376 where lower(left(title,8))='kirosaku';
update asin set brand_id=128 where lower(left(title,8))='kidzlane';
update asin set brand_id=500 where lower(left(title,9))='kids rule';
update asin set brand_id=184 where lower(left(title,5))='kicko';
update asin set brand_id=175 where lower(left(title,16))='kettlebell kings';
update asin set brand_id=161 where lower(left(title,6))='kelana';
update asin set brand_id=156 where lower(left(title,7))='kedudes';
update asin set brand_id=467 where lower(left(title,3))='kcg';
update asin set brand_id=178 where lower(left(title,6))='katzco';
update asin set brand_id=499 where lower(left(title,5))='kassa';
update asin set brand_id=407 where lower(left(title,6))='kascin';
update asin set brand_id=22 where lower(left(title,17))='karnival costumes';
update asin set brand_id=24 where lower(left(title,11))='juvolicious';
update asin set brand_id=3 where lower(left(title,6))='juvale';
update asin set brand_id=54 where lower(left(title,6))='judees';
update asin set brand_id=476 where lower(left(title,6))='jilong';
update asin set brand_id=190 where lower(left(title,11))='jewelkeeper';
update asin set brand_id=498 where lower(left(title,9))='jessi mae';
update asin set brand_id=262 where lower(left(title,7))='jaxojoy';
update asin set brand_id=260 where lower(left(title,8))='jardinax';
update asin set brand_id=322 where lower(left(title,10))='jardimanía';
update asin set brand_id=402 where lower(left(title,8))='jansport';
update asin set brand_id=379 where lower(left(title,8))='ivy step';
update asin set brand_id=82 where lower(left(title,7))='isavera';
update asin set brand_id=135 where lower(left(title,7))='iprimio';
update asin set brand_id=25 where lower(left(title,4))='ionx';
update asin set brand_id=14 where lower(left(title,16))='invitation paper';
update asin set brand_id=53 where lower(left(title,6))='insten';
update asin set brand_id=111 where lower(left(title,11))='installgear';
update asin set brand_id=474 where lower(left(title,7))='innuovo';
update asin set brand_id=348 where lower(left(title,13))='innovativemap';
update asin set brand_id=87 where lower(left(title,13))='infinity soil';
update asin set brand_id=424 where lower(left(title,8))='infinity';
update asin set brand_id=7 where lower(left(title,18))='infinite curiosity';
update asin set brand_id=8 where lower(left(title,7))='impresa';
update asin set brand_id=319 where lower(left(title,17))='illumisafe lights';
update asin set brand_id=418 where lower(left(title,14))='igadget london';
update asin set brand_id=395 where lower(left(title,6))='ifancy';
update asin set brand_id=239 where lower(left(title,7))='iceberk';
update asin set brand_id=212 where lower(left(title,18))='hynec technologies';
update asin set brand_id=134 where lower(left(title,7))='hydrate';
update asin set brand_id=344 where lower(left(title,7))='hunnibi';
update asin set brand_id=372 where lower(left(title,18))='hubble bubble kids';
update asin set brand_id=228 where lower(left(title,6))='hotpop';
update asin set brand_id=139 where lower(left(title,7))='hotlite';
update asin set brand_id=229 where lower(left(title,10))='hot target';
update asin set brand_id=255 where lower(left(title,15))='homestead honey';
update asin set brand_id=362 where lower(left(title,15))='homemaid living';
update asin set brand_id=308 where lower(left(title,13))='home organics';
update asin set brand_id=84 where lower(left(title,13))='home decision';
update asin set brand_id=497 where lower(left(title,9))='home & me';
update asin set brand_id=305 where lower(left(title,8))='homarden';
update asin set brand_id=421 where lower(left(title,14))='holiday spirit';
update asin set brand_id=343 where lower(left(title,12))='holi natural';
update asin set brand_id=83 where lower(left(title,8))='hog wash';
update asin set brand_id=458 where lower(left(title,4))='hkkb';
update asin set brand_id=377 where lower(left(title,9))='hk gaming';
update asin set brand_id=172 where lower(left(title,8))='highwind';
update asin set brand_id=183 where lower(left(title,10))='high pulse';
update asin set brand_id=248 where lower(left(title,6))='heynna';
update asin set brand_id=153 where lower(left(title,7))='hertzko';
update asin set brand_id=340 where lower(left(title,15))='hearts & crafts';
update asin set brand_id=129 where lower(left(title,32))='health priority natural products';
update asin set brand_id=244 where lower(left(title,6))='hawwwy';
update asin set brand_id=468 where lower(left(title,22))='haushalt international';
update asin set brand_id=299 where lower(left(title,7))='happypo';
update asin set brand_id=226 where lower(left(title,8))='happilax';
update asin set brand_id=165 where lower(left(title,9))='hangorize';
update asin set brand_id=198 where lower(left(title,14))='hamilton hills';
update asin set brand_id=39 where lower(left(title,6))='hamama';
update asin set brand_id=350 where lower(left(title,7))='hallops';
update asin set brand_id=387 where lower(left(title,6))='gymbee';
update asin set brand_id=70 where lower(left(title,4))='gym1';
update asin set brand_id=276 where lower(left(title,12))='gutter games';
update asin set brand_id=463 where lower(left(title,7))='grundig';
update asin set brand_id=120 where lower(left(title,11))='grippi ring';
update asin set brand_id=293 where lower(left(title,8))='grillman';
update asin set brand_id=335 where lower(left(title,11))='grill trade';
update asin set brand_id=130 where lower(left(title,7))='greenco';
update asin set brand_id=333 where lower(left(title,13))='gran shopping';
update asin set brand_id=78 where lower(left(title,15))='graham products';
update asin set brand_id=27 where lower(left(title,8))='grabease';
update asin set brand_id=396 where lower(left(title,9))='gourmesso';
update asin set brand_id=141 where lower(left(title,14))='gold lion gear';
update asin set brand_id=451 where lower(left(title,12))='go on the go';
update asin set brand_id=6 where lower(left(title,8))='glamlily';
update asin set brand_id=52 where lower(left(title,8))='girlzone';
update asin set brand_id=313 where lower(left(title,8))='genskins';
update asin set brand_id=95 where lower(left(title,12))='genie crafts';
update asin set brand_id=232 where lower(left(title,8))='geekdigg';
update asin set brand_id=392 where lower(left(title,7))='gateron';
update asin set brand_id=171 where lower(left(title,6))='g-rack';
update asin set brand_id=123 where lower(left(title,11))='fuxion toys';
update asin set brand_id=261 where lower(left(title,13))='fuxion sports';
update asin set brand_id=459 where lower(left(title,9))='furemover';
update asin set brand_id=89 where lower(left(title,12))='friday 7care';
update asin set brand_id=79 where lower(left(title,18))='fountain city soap';
update asin set brand_id=345 where lower(left(title,8))='flygrubs';
update asin set brand_id=222 where lower(left(title,7))='flybold';
update asin set brand_id=309 where lower(left(title,10))='flexi hose';
update asin set brand_id=483 where lower(left(title,17))='flatten the curve';
update asin set brand_id=338 where lower(left(title,17))='flathead products';
update asin set brand_id=430 where lower(left(title,7))='flamely';
update asin set brand_id=365 where lower(left(title,11))='firebuilder';
update asin set brand_id=235 where lower(left(title,6))='fidelo';
update asin set brand_id=26 where lower(left(title,8))='fauxreal';
update asin set brand_id=16 where lower(left(title,9))='faux real';
update asin set brand_id=496 where lower(left(title,13))='farmlyn creek';
update asin set brand_id=453 where lower(left(title,15))='farmhouse honey';
update asin set brand_id=495 where lower(left(title,14))='faithful finds';
update asin set brand_id=368 where lower(left(title,17))='fairytale wedding';
update asin set brand_id=34 where lower(left(title,7))='eyebloc';
update asin set brand_id=51 where lower(left(title,20))='exterminators choice';
update asin set brand_id=124 where lower(left(title,9))='evolution';
update asin set brand_id=103 where lower(left(title,7))='everloc';
update asin set brand_id=11 where lower(left(title,22))='evergreen pet supplies';
update asin set brand_id=162 where lower(left(title,13))='even naturals';
update asin set brand_id=133 where lower(left(title,6))='estilo';
update asin set brand_id=494 where lower(left(title,9))='epiqueone';
update asin set brand_id=125 where lower(left(title,6))='enovoe';
update asin set brand_id=307 where lower(left(title,10))='enno vatti';
update asin set brand_id=317 where lower(left(title,17))='effekt manufaktur';
update asin set brand_id=378 where lower(left(title,4))='edou';
update asin set brand_id=414 where lower(left(title,8))='edelhand';
update asin set brand_id=484 where lower(left(title,3))='eda';
update asin set brand_id=42 where lower(left(title,13))='eco amenities';
update asin set brand_id=266 where lower(left(title,5))='ebung';
update asin set brand_id=264 where lower(left(title,5))='eberg';
update asin set brand_id=210 where lower(left(title,8))='eberbart';
update asin set brand_id=425 where lower(left(title,15))='ebe emmasbyemma';
update asin set brand_id=385 where lower(left(title,10))='easy gleam';
update asin set brand_id=431 where lower(left(title,10))='east creek';
update asin set brand_id=278 where lower(left(title,12))='dynamic gear';
update asin set brand_id=269 where lower(left(title,7))='dylonic';
update asin set brand_id=324 where lower(left(title,6))='durgod';
update asin set brand_id=297 where lower(left(title,8))='duracare';
update asin set brand_id=354 where lower(left(title,9))='dreamship';
update asin set brand_id=342 where lower(left(title,11))='dr. wellthy';
update asin set brand_id=107 where lower(left(title,7))='dorence';
update asin set brand_id=366 where lower(left(title,13))='doradreamdeko';
update asin set brand_id=254 where lower(left(title,8))='donbolso';
update asin set brand_id=68 where lower(left(title,11))='dodo babies';
update asin set brand_id=69 where lower(left(title,9))='diy gifts';
update asin set brand_id=62 where lower(left(title,8))='dew well';
update asin set brand_id=492 where lower(left(title,7))='de-bird';
update asin set brand_id=193 where lower(left(title,5))='ddoxx';
update asin set brand_id=384 where lower(left(title,7))='dazmers';
update asin set brand_id=100 where lower(left(title,13))='dawhud direct';
update asin set brand_id=493 where lower(left(title,12))='curious chef';
update asin set brand_id=157 where lower(left(title,8))='cucisina';
update asin set brand_id=233 where lower(left(title,9))='crown led';
update asin set brand_id=45 where lower(left(title,9))='crenstone';
update asin set brand_id=35 where lower(left(title,11))='creative qt';
update asin set brand_id=114 where lower(left(title,14))='crave naturals';
update asin set brand_id=197 where lower(left(title,9))='craftopia';
update asin set brand_id=32 where lower(left(title,7))='cozyway';
update asin set brand_id=36 where lower(left(title,12))='country silk';
update asin set brand_id=20 where lower(left(title,19))='cottage creek farms';
update asin set brand_id=149 where lower(left(title,15))='comfy clothiers';
update asin set brand_id=72 where lower(left(title,10))='cobble pro';
update asin set brand_id=433 where lower(left(title,9))='cloudspot';
update asin set brand_id=136 where lower(left(title,13))='click n'' play';
update asin set brand_id=75 where lower(left(title,16))='clever creations';
update asin set brand_id=77 where lower(left(title,11))='clever chef';
update asin set brand_id=201 where lower(left(title,6))='cinch!';
update asin set brand_id=251 where lower(left(title,18))='childlike behavior';
update asin set brand_id=294 where lower(left(title,13))='charles daily';
update asin set brand_id=286 where lower(left(title,10))='casingwise';
update asin set brand_id=182 where lower(left(title,10))='care touch';
update asin set brand_id=265 where lower(left(title,10))='care check';
update asin set brand_id=249 where lower(left(title,10))='cali white';
update asin set brand_id=47 where lower(left(title,15))='butterfly craze';
update asin set brand_id=405 where lower(left(title,9))='burgstein';
update asin set brand_id=394 where lower(left(title,12))='buntes brett';
update asin set brand_id=131 where lower(left(title,8))='bullwork';
update asin set brand_id=491 where lower(left(title,16))='built industrial';
update asin set brand_id=352 where lower(left(title,8))='build me';
update asin set brand_id=490 where lower(left(title,5))='bryte';
update asin set brand_id=163 where lower(left(title,9))='brynnberg';
update asin set brand_id=40 where lower(left(title,11))='brush dance';
update asin set brand_id=147 where lower(left(title,8))='bruntmor';
update asin set brand_id=355 where lower(left(title,11))='brite crown';
update asin set brand_id=217 where lower(left(title,19))='brilliant evolution';
update asin set brand_id=4 where lower(left(title,16))='bright creations';
update asin set brand_id=74 where lower(left(title,15))='brew your bucha';
update asin set brand_id=191 where lower(left(title,13))='boulder tools';
update asin set brand_id=312 where lower(left(title,7))='botabee';
update asin set brand_id=409 where lower(left(title,11))='booty wipes';
update asin set brand_id=471 where lower(left(title,22))='bootiful carving tools';
update asin set brand_id=288 where lower(left(title,7))='bonorum';
update asin set brand_id=224 where lower(left(title,12))='bolt dropper';
update asin set brand_id=230 where lower(left(title,9))='body mate';
update asin set brand_id=241 where lower(left(title,11))='board geeks';
update asin set brand_id=205 where lower(left(title,5))='bnext';
update asin set brand_id=2 where lower(left(title,10))='blue panda';
update asin set brand_id=185 where lower(left(title,11))='black rhino';
update asin set brand_id=159 where lower(left(title,12))='bird blinder';
update asin set brand_id=188 where lower(left(title,13))='bins & things';
update asin set brand_id=277 where lower(left(title,13))='bigtime signs';
update asin set brand_id=448 where lower(left(title,15))='bigtime designs';
update asin set brand_id=204 where lower(left(title,15))='big red rooster';
update asin set brand_id=118 where lower(left(title,7))='bestway';
update asin set brand_id=489 where lower(left(title,20))='best paper greetings';
update asin set brand_id=337 where lower(left(title,9))='bellmietz';
update asin set brand_id=142 where lower(left(title,10))='bellanails';
update asin set brand_id=281 where lower(left(title,12))='bella & balu';
update asin set brand_id=427 where lower(left(title,8))='beeleeve';
update asin set brand_id=325 where lower(left(title,11))='beautyworks';
update asin set brand_id=236 where lower(left(title,24))='beast cooler accessories';
update asin set brand_id=310 where lower(left(title,7))='beartop';
update asin set brand_id=37 where lower(left(title,10))='bearington';
update asin set brand_id=164 where lower(left(title,6))='beachr';
update asin set brand_id=441 where lower(left(title,4))='baäb';
update asin set brand_id=152 where lower(left(title,7))='barvivo';
update asin set brand_id=208 where lower(left(title,9))='barrakuda';
update asin set brand_id=435 where lower(left(title,26))='barkmaster bbq accessories';
update asin set brand_id=247 where lower(left(title,11))='banana bike';
update asin set brand_id=280 where lower(left(title,6))='bamodi';
update asin set brand_id=275 where lower(left(title,5))='bamgo';
update asin set brand_id=363 where lower(left(title,6))='balder';
update asin set brand_id=195 where lower(left(title,8))='bahidora';
update asin set brand_id=250 where lower(left(title,8))='babyleaf';
update asin set brand_id=480 where lower(left(title,29))='baby merlin''s magic sleepsuit';
update asin set brand_id=158 where lower(left(title,5))='azmed';
update asin set brand_id=252 where lower(left(title,21))='aya''s cutlery kingdom';
update asin set brand_id=209 where lower(left(title,15))='aviano hardware';
update asin set brand_id=268 where lower(left(title,6))='aviano';
update asin set brand_id=300 where lower(left(title,7))='auxesia';
update asin set brand_id=298 where lower(left(title,11))='aulett home';
update asin set brand_id=140 where lower(left(title,6))='attrac';
update asin set brand_id=488 where lower(left(title,9))='artellius';
update asin set brand_id=295 where lower(left(title,8))='armogear';
update asin set brand_id=121 where lower(left(title,12))='argan deluxe';
update asin set brand_id=91 where lower(left(title,7))='aqulius';
update asin set brand_id=38 where lower(left(title,7))='aquapaw';
update asin set brand_id=259 where lower(left(title,10))='amped & co';
update asin set brand_id=194 where lower(left(title,5))='amazy';
update asin set brand_id=332 where lower(left(title,13))='alpine choice';
update asin set brand_id=113 where lower(left(title,8))='all ride';
update asin set brand_id=102 where lower(left(title,8))='aleratec';
update asin set brand_id=374 where lower(left(title,8))='agreenie';
update asin set brand_id=112 where lower(left(title,6))='adidas';
update asin set brand_id=67 where lower(left(title,14))='ad rescue wear';
update asin set brand_id=48 where lower(left(title,7))='aculief';
update asin set brand_id=29 where lower(left(title,10))='activ life';
update asin set brand_id=383 where lower(left(title,12))='actif sports';
update asin set brand_id=438 where lower(left(title,6))='acoway';
update asin set brand_id=457 where lower(left(title,6))='acotop';
update asin set brand_id=331 where lower(left(title,8))='accutire';
update asin set brand_id=166 where lower(left(title,6))='abflex';
update asin set brand_id=192 where lower(left(title,9))='abco tech';
update asin set brand_id=454 where lower(left(title,8))='a.i.& e.';
update asin set brand_id=50 where lower(left(title,6))='a team';
update asin set brand_id=403 where lower(left(title,6))='3 bros';
update asin set brand_id=138 where lower(left(title,5))='2wayz';
update asin set brand_id=173 where lower(left(title,11))='2 lb. depot';
update asin set brand_id=346 where lower(left(name,8))='zorestar';
update asin set brand_id=93 where lower(left(name,6))='zodaca';
update asin set brand_id=215 where lower(left(name,7))='zap it!';
update asin set brand_id=450 where lower(left(name,4))='zaos';
update asin set brand_id=304 where lower(left(name,6))='yumaya';
update asin set brand_id=461 where lower(left(name,6))='yoyork';
update asin set brand_id=80 where lower(left(name,13))='yankee candle';
update asin set brand_id=443 where lower(left(name,9))='wow! pods';
update asin set brand_id=146 where lower(left(name,9))='wood grip';
update asin set brand_id=41 where lower(left(name,10))='wod nation';
update asin set brand_id=347 where lower(left(name,15))='winning fingers';
update asin set brand_id=444 where lower(left(name,7))='windsor';
update asin set brand_id=99 where lower(left(name,13))='window garden';
update asin set brand_id=397 where lower(left(name,13))='wildtier herz';
update asin set brand_id=406 where lower(left(name,15))='wildlife friend';
update asin set brand_id=225 where lower(left(name,20))='wild wolf outfitters';
update asin set brand_id=108 where lower(left(name,25))='wholesale plumbing supply';
update asin set brand_id=316 where lower(left(name,16))='whole housewares';
update asin set brand_id=119 where lower(left(name,12))='whizzy wheel';
update asin set brand_id=470 where lower(left(name,10))='white coat';
update asin set brand_id=514 where lower(left(name,9))='wellbrite';
update asin set brand_id=339 where lower(left(name,7))='watergo';
update asin set brand_id=455 where lower(left(name,6))='vp tek';
update asin set brand_id=357 where lower(left(name,7))='vp home';
update asin set brand_id=220 where lower(left(name,9))='vorfreude';
update asin set brand_id=456 where lower(left(name,7))='voltada';
update asin set brand_id=513 where lower(left(name,13))='vine homecare';
update asin set brand_id=274 where lower(left(name,8))='viirkuja';
update asin set brand_id=270 where lower(left(name,9))='vibo care';
update asin set brand_id=428 where lower(left(name,17))='verymerrymakering';
update asin set brand_id=117 where lower(left(name,6))='vdomus';
update asin set brand_id=386 where lower(left(name,11))='value grubs';
update asin set brand_id=512 where lower(left(name,4))='vaci';
update asin set brand_id=143 where lower(left(name,5))='uulki';
update asin set brand_id=289 where lower(left(name,12))='urbanfit pro';
update asin set brand_id=440 where lower(left(name,10))='urban tech';
update asin set brand_id=390 where lower(left(name,12))='urban design';
update asin set brand_id=287 where lower(left(name,11))='upper order';
update asin set brand_id=21 where lower(left(name,11))='untamed sox';
update asin set brand_id=511 where lower(left(name,6))='unokki';
update asin set brand_id=449 where lower(left(name,9))='unbekannt';
update asin set brand_id=258 where lower(left(name,10))='tunephonik';
update asin set brand_id=137 where lower(left(name,18))='truremedy naturals';
update asin set brand_id=436 where lower(left(name,9))='tribe wod';
update asin set brand_id=196 where lower(left(name,8))='tresalto';
update asin set brand_id=510 where lower(left(name,10))='travelwell';
update asin set brand_id=199 where lower(left(name,8))='travelax';
update asin set brand_id=439 where lower(left(name,12))='travel elite';
update asin set brand_id=256 where lower(left(name,14))='tranquilbeauty';
update asin set brand_id=473 where lower(left(name,9))='trainmate';
update asin set brand_id=145 where lower(left(name,8))='top race';
update asin set brand_id=221 where lower(left(name,9))='toolzilla';
update asin set brand_id=90 where lower(left(name,8))='toodaloo';
update asin set brand_id=203 where lower(left(name,17))='tobe readyforlife';
update asin set brand_id=55 where lower(left(name,13))='tickle & main';
update asin set brand_id=408 where lower(left(name,8))='thingles';
update asin set brand_id=388 where lower(left(name,8))='the shop';
update asin set brand_id=306 where lower(left(name,11))='the gym keg';
update asin set brand_id=15 where lower(left(name,21))='the gifted stationery';
update asin set brand_id=63 where lower(left(name,20))='the cocktail box co.';
update asin set brand_id=367 where lower(left(name,21))='the battery organizer';
update asin set brand_id=65 where lower(left(name,13))='tf publishing';
update asin set brand_id=181 where lower(left(name,10))='telefunken';
update asin set brand_id=391 where lower(left(name,7))='tastory';
update asin set brand_id=509 where lower(left(name,8))='tapeplus';
update asin set brand_id=370 where lower(left(name,36))='tame the wild make your beard behave';
update asin set brand_id=30 where lower(left(name,16))='talented kitchen';
update asin set brand_id=17 where lower(left(name,8))='tadpoles';
update asin set brand_id=422 where lower(left(name,5))='sølmo';
update asin set brand_id=432 where lower(left(name,8))='swoopies';
update asin set brand_id=380 where lower(left(name,14))='swiss outdoors';
update asin set brand_id=508 where lower(left(name,16))='sweet vibrations';
update asin set brand_id=283 where lower(left(name,11))='sweet vibes';
update asin set brand_id=353 where lower(left(name,12))='sweet ponies';
update asin set brand_id=92 where lower(left(name,21))='sustainable greetings';
update asin set brand_id=81 where lower(left(name,8))='supplift';
update asin set brand_id=207 where lower(left(name,7))='sunglow';
update asin set brand_id=381 where lower(left(name,10))='summit one';
update asin set brand_id=28 where lower(left(name,14))='strictly briks';
update asin set brand_id=105 where lower(left(name,9))='stravilio';
update asin set brand_id=5 where lower(left(name,14))='stockroom plus';
update asin set brand_id=109 where lower(left(name,9))='stepngrip';
update asin set brand_id=216 where lower(left(name,12))='steadydoggie';
update asin set brand_id=59 where lower(left(name,5))='stead';
update asin set brand_id=399 where lower(left(name,22))='starbright grill light';
update asin set brand_id=170 where lower(left(name,10))='star right';
update asin set brand_id=361 where lower(left(name,13))='squeeze craft';
update asin set brand_id=413 where lower(left(name,10))='sportanics';
update asin set brand_id=507 where lower(left(name,14))='spooky central';
update asin set brand_id=371 where lower(left(name,8))='spaßwerk';
update asin set brand_id=10 where lower(left(name,16))='sparkle and bash';
update asin set brand_id=150 where lower(left(name,10))='spacesaver';
update asin set brand_id=180 where lower(left(name,9))='space max';
update asin set brand_id=18 where lower(left(name,5))='soxxo';
update asin set brand_id=303 where lower(left(name,12))='sousvide art';
update asin set brand_id=73 where lower(left(name,4))='sony';
update asin set brand_id=326 where lower(left(name,6))='somera';
update asin set brand_id=329 where lower(left(name,9))='sofamatch';
update asin set brand_id=267 where lower(left(name,8))='socialic';
update asin set brand_id=442 where lower(left(name,13))='snug a babies';
update asin set brand_id=110 where lower(left(name,8))='smartweb';
update asin set brand_id=272 where lower(left(name,9))='smartpeas';
update asin set brand_id=330 where lower(left(name,25))='slokey discover the world';
update asin set brand_id=174 where lower(left(name,10))='sliptogrip';
update asin set brand_id=485 where lower(left(name,12))='slight touch';
update asin set brand_id=227 where lower(left(name,9))='sleepingo';
update asin set brand_id=506 where lower(left(name,17))='sleeping partners';
update asin set brand_id=279 where lower(left(name,16))='sir marlon grant';
update asin set brand_id=505 where lower(left(name,13))='simply genius';
update asin set brand_id=320 where lower(left(name,6))='silvon';
update asin set brand_id=167 where lower(left(name,15))='signs authority';
update asin set brand_id=417 where lower(left(name,16))='signature living';
update asin set brand_id=214 where lower(left(name,16))='signature garden';
update asin set brand_id=472 where lower(left(name,15))='shirt stay plus';
update asin set brand_id=423 where lower(left(name,16))='serene evolution';
update asin set brand_id=213 where lower(left(name,5))='schon';
update asin set brand_id=360 where lower(left(name,8))='schoberg';
update asin set brand_id=106 where lower(left(name,6))='sauder';
update asin set brand_id=169 where lower(left(name,6))='satina';
update asin set brand_id=412 where lower(left(name,9))='saniverde';
update asin set brand_id=504 where lower(left(name,9))='sameriver';
update asin set brand_id=311 where lower(left(name,9))='safestrap';
update asin set brand_id=420 where lower(left(name,5))='s-mag';
update asin set brand_id=240 where lower(left(name,5))='ryher';
update asin set brand_id=43 where lower(left(name,13))='running buddy';
update asin set brand_id=19 where lower(left(name,11))='rose cheeks';
update asin set brand_id=96 where lower(left(name,17))='room/dividers/now';
update asin set brand_id=23 where lower(left(name,6))='ri pac';
update asin set brand_id=315 where lower(left(name,17))='regal trunk & co.';
update asin set brand_id=56 where lower(left(name,16))='real good coffee';
update asin set brand_id=477 where lower(left(name,9))='readerest';
update asin set brand_id=358 where lower(left(name,7))='rawbond';
update asin set brand_id=445 where lower(left(name,4))='raia';
update asin set brand_id=71 where lower(left(name,7))='radiate';
update asin set brand_id=231 where lower(left(name,14))='quality contor';
update asin set brand_id=291 where lower(left(name,6))='purava';
update asin set brand_id=179 where lower(left(name,17))='prosumer''s choice';
update asin set brand_id=469 where lower(left(name,8))='prosteam';
update asin set brand_id=415 where lower(left(name,13))='prosper honey';
update asin set brand_id=160 where lower(left(name,7))='prodive';
update asin set brand_id=88 where lower(left(name,8))='prodepot';
update asin set brand_id=273 where lower(left(name,8))='prodarts';
update asin set brand_id=151 where lower(left(name,14))='pro bike tools';
update asin set brand_id=464 where lower(left(name,8))='prexware';
update asin set brand_id=101 where lower(left(name,7))='prextex';
update asin set brand_id=284 where lower(left(name,12))='pretty kitty';
update asin set brand_id=98 where lower(left(name,7))='prestee';
update asin set brand_id=359 where lower(left(name,12))='present mind';
update asin set brand_id=206 where lower(left(name,24))='precision quilting tools';
update asin set brand_id=104 where lower(left(name,5))='powrx';
update asin set brand_id=31 where lower(left(name,17))='powerstone pumice';
update asin set brand_id=290 where lower(left(name,8))='poweroni';
update asin set brand_id=336 where lower(left(name,10))='power pins';
update asin set brand_id=144 where lower(left(name,11))='power & co.';
update asin set brand_id=246 where lower(left(name,9))='portovino';
update asin set brand_id=237 where lower(left(name,5))='popco';
update asin set brand_id=302 where lower(left(name,7))='plemont';
update asin set brand_id=465 where lower(left(name,8))='playmind';
update asin set brand_id=177 where lower(left(name,10))='pixiecrush';
update asin set brand_id=503 where lower(left(name,12))='pipilo press';
update asin set brand_id=148 where lower(left(name,15))='pine tree tools';
update asin set brand_id=334 where lower(left(name,11))='pfotenolymp';
update asin set brand_id=292 where lower(left(name,9))='pet union';
update asin set brand_id=66 where lower(left(name,16))='pet prep academy';
update asin set brand_id=318 where lower(left(name,6))='pesani';
update asin set brand_id=202 where lower(left(name,20))='penguin art supplies';
update asin set brand_id=460 where lower(left(name,9))='pee buddy';
update asin set brand_id=85 where lower(left(name,14))='pebble & crane';
update asin set brand_id=373 where lower(left(name,11))='pardo cigar';
update asin set brand_id=1 where lower(left(name,12))='paper junkie';
update asin set brand_id=263 where lower(left(name,10))='paint mark';
update asin set brand_id=375 where lower(left(name,8))='owngrown';
update asin set brand_id=404 where lower(left(name,9))='overgrill';
update asin set brand_id=419 where lower(left(name,7))='outlery';
update asin set brand_id=271 where lower(left(name,13))='outdoor panda';
update asin set brand_id=321 where lower(left(name,5))='osaka';
update asin set brand_id=44 where lower(left(name,19))='original stationery';
update asin set brand_id=341 where lower(left(name,8))='oraganix';
update asin set brand_id=127 where lower(left(name,15))='open seed vault';
update asin set brand_id=245 where lower(left(name,9))='old nobby';
update asin set brand_id=94 where lower(left(name,13))='okuna outpost';
update asin set brand_id=356 where lower(left(name,17))='officeworld range';
update asin set brand_id=328 where lower(left(name,10))='officeline';
update asin set brand_id=502 where lower(left(name,6))='octago';
update asin set brand_id=382 where lower(left(name,7))='nutrani';
update asin set brand_id=60 where lower(left(name,17))='nurse and nourish';
update asin set brand_id=410 where lower(left(name,10))='novastreet';
update asin set brand_id=189 where lower(left(name,20))='nourished essentials';
update asin set brand_id=122 where lower(left(name,15))='not razor owned';
update asin set brand_id=116 where lower(left(name,9))='noa store';
update asin set brand_id=187 where lower(left(name,4))='nezt';
update asin set brand_id=242 where lower(left(name,10))='neomagnova';
update asin set brand_id=218 where lower(left(name,7))='neliblu';
update asin set brand_id=429 where lower(left(name,13))='naturschmiede';
update asin set brand_id=219 where lower(left(name,20))='national electronics';
update asin set brand_id=211 where lower(left(name,3))='nan';
update asin set brand_id=482 where lower(left(name,3))='n/a';
update asin set brand_id=168 where lower(left(name,18))='my cinema lightbox';
update asin set brand_id=437 where lower(left(name,8))='mr. pets';
update asin set brand_id=86 where lower(left(name,29))='mountain mike''s reproductions';
update asin set brand_id=97 where lower(left(name,17))='mountain grillers';
update asin set brand_id=234 where lower(left(name,17))='modern industrial';
update asin set brand_id=400 where lower(left(name,7))='mode 33';
update asin set brand_id=426 where lower(left(name,5))='mizar';
update asin set brand_id=115 where lower(left(name,8))='mister m';
update asin set brand_id=501 where lower(left(name,18))='mission automotive';
update asin set brand_id=349 where lower(left(name,12))='mighty bliss';
update asin set brand_id=49 where lower(left(name,5))='merka';
update asin set brand_id=411 where lower(left(name,10))='meistergut';
update asin set brand_id=475 where lower(left(name,7))='medikit';
update asin set brand_id=296 where lower(left(name,10))='meant2tobe';
update asin set brand_id=416 where lower(left(name,13))='matilda & co.';
update asin set brand_id=369 where lower(left(name,13))='master maison';
update asin set brand_id=327 where lower(left(name,5))='masho';
update asin set brand_id=257 where lower(left(name,9))='markenlos';
update asin set brand_id=58 where lower(left(name,13))='marble genius';
update asin set brand_id=9 where lower(left(name,10))='maplefield';
update asin set brand_id=301 where lower(left(name,5))='mango';
update asin set brand_id=282 where lower(left(name,8))='makimaja';
update asin set brand_id=57 where lower(left(name,15))='magnificent 101';
update asin set brand_id=64 where lower(left(name,7))='magneto';
update asin set brand_id=478 where lower(left(name,12))='magnet build';
update asin set brand_id=481 where lower(left(name,15))='magic sleepsuit';
update asin set brand_id=132 where lower(left(name,14))='madison supply';

update asin set brand_id=479 where lower(left(name,7))='luminrg';
update asin set brand_id=154 where lower(left(name,6))='lumare';
update asin set brand_id=155 where lower(left(name,10))='long gamma';
update asin set brand_id=186 where lower(left(name,11))='lock cowboy';
update asin set brand_id=434 where lower(left(name,7))='livonir';
update asin set brand_id=223 where lower(left(name,6))='livaia';
update asin set brand_id=398 where lower(left(name,16))='little moonshine';
update asin set brand_id=253 where lower(left(name,12))='litti pritti';
update asin set brand_id=446 where lower(left(name,10))='litti city';

update asin set brand_id=33 where lower(left(name,10))='lilgadgets';
update asin set brand_id=452 where lower(left(name,5))='liivo';
update asin set brand_id=364 where lower(left(name,12))='light autumn';
update asin set brand_id=46 where lower(left(name,11))='life mounts';
update asin set brand_id=389 where lower(left(name,10))='liebspecht';
update asin set brand_id=447 where lower(left(name,6))='libken';
update asin set brand_id=323 where lower(left(name,8))='li''l-gen';
update asin set brand_id=126 where lower(left(name,6))='lennox';
update asin set brand_id=13 where lower(left(name,7))='le juvo';
update asin set brand_id=401 where lower(left(name,11))='laxe handle';
update asin set brand_id=285 where lower(left(name,7))='lavodia';
update asin set brand_id=466 where lower(left(name,7))='lavault';
update asin set brand_id=393 where lower(left(name,10))='lava sport';
update asin set brand_id=61 where lower(left(name,8))='lascoota';
update asin set brand_id=243 where lower(left(name,5))='laevo';
update asin set brand_id=486 where lower(left(name,28))='l&amp;g london uniforms u.k.';
update asin set brand_id=200 where lower(left(name,6))='knitiq';
update asin set brand_id=351 where lower(left(name,8))='kitchtic';
update asin set brand_id=462 where lower(left(name,11))='kitchenzone';
update asin set brand_id=176 where lower(left(name,13))='kitchen gizmo';
update asin set brand_id=376 where lower(left(name,8))='kirosaku';
update asin set brand_id=128 where lower(left(name,8))='kidzlane';
update asin set brand_id=500 where lower(left(name,9))='kids rule';
update asin set brand_id=184 where lower(left(name,5))='kicko';
update asin set brand_id=175 where lower(left(name,16))='kettlebell kings';
update asin set brand_id=161 where lower(left(name,6))='kelana';
update asin set brand_id=156 where lower(left(name,7))='kedudes';
update asin set brand_id=467 where lower(left(name,3))='kcg';
update asin set brand_id=178 where lower(left(name,6))='katzco';
update asin set brand_id=499 where lower(left(name,5))='kassa';
update asin set brand_id=407 where lower(left(name,6))='kascin';
update asin set brand_id=22 where lower(left(name,17))='karnival costumes';
update asin set brand_id=24 where lower(left(name,11))='juvolicious';
update asin set brand_id=3 where lower(left(name,6))='juvale';
update asin set brand_id=54 where lower(left(name,6))='judees';
update asin set brand_id=476 where lower(left(name,6))='jilong';
update asin set brand_id=190 where lower(left(name,11))='jewelkeeper';
update asin set brand_id=498 where lower(left(name,9))='jessi mae';
update asin set brand_id=262 where lower(left(name,7))='jaxojoy';
update asin set brand_id=260 where lower(left(name,8))='jardinax';
update asin set brand_id=322 where lower(left(name,10))='jardimanía';
update asin set brand_id=402 where lower(left(name,8))='jansport';
update asin set brand_id=379 where lower(left(name,8))='ivy step';
update asin set brand_id=82 where lower(left(name,7))='isavera';
update asin set brand_id=135 where lower(left(name,7))='iprimio';
update asin set brand_id=25 where lower(left(name,4))='ionx';
update asin set brand_id=14 where lower(left(name,16))='invitation paper';
update asin set brand_id=53 where lower(left(name,6))='insten';
update asin set brand_id=111 where lower(left(name,11))='installgear';
update asin set brand_id=474 where lower(left(name,7))='innuovo';
update asin set brand_id=348 where lower(left(name,13))='innovativemap';
update asin set brand_id=87 where lower(left(name,13))='infinity soil';
update asin set brand_id=424 where lower(left(name,8))='infinity';
update asin set brand_id=7 where lower(left(name,18))='infinite curiosity';
update asin set brand_id=8 where lower(left(name,7))='impresa';
update asin set brand_id=319 where lower(left(name,17))='illumisafe lights';
update asin set brand_id=418 where lower(left(name,14))='igadget london';
update asin set brand_id=395 where lower(left(name,6))='ifancy';
update asin set brand_id=239 where lower(left(name,7))='iceberk';
update asin set brand_id=212 where lower(left(name,18))='hynec technologies';
update asin set brand_id=134 where lower(left(name,7))='hydrate';
update asin set brand_id=344 where lower(left(name,7))='hunnibi';
update asin set brand_id=372 where lower(left(name,18))='hubble bubble kids';
update asin set brand_id=228 where lower(left(name,6))='hotpop';
update asin set brand_id=139 where lower(left(name,7))='hotlite';
update asin set brand_id=229 where lower(left(name,10))='hot target';
update asin set brand_id=255 where lower(left(name,15))='homestead honey';
update asin set brand_id=362 where lower(left(name,15))='homemaid living';
update asin set brand_id=308 where lower(left(name,13))='home organics';
update asin set brand_id=84 where lower(left(name,13))='home decision';
update asin set brand_id=497 where lower(left(name,9))='home & me';
update asin set brand_id=305 where lower(left(name,8))='homarden';
update asin set brand_id=421 where lower(left(name,14))='holiday spirit';
update asin set brand_id=343 where lower(left(name,12))='holi natural';
update asin set brand_id=83 where lower(left(name,8))='hog wash';
update asin set brand_id=458 where lower(left(name,4))='hkkb';
update asin set brand_id=377 where lower(left(name,9))='hk gaming';
update asin set brand_id=172 where lower(left(name,8))='highwind';
update asin set brand_id=183 where lower(left(name,10))='high pulse';
update asin set brand_id=248 where lower(left(name,6))='heynna';
update asin set brand_id=153 where lower(left(name,7))='hertzko';
update asin set brand_id=340 where lower(left(name,15))='hearts & crafts';
update asin set brand_id=129 where lower(left(name,32))='health priority natural products';
update asin set brand_id=244 where lower(left(name,6))='hawwwy';
update asin set brand_id=468 where lower(left(name,22))='haushalt international';
update asin set brand_id=299 where lower(left(name,7))='happypo';
update asin set brand_id=226 where lower(left(name,8))='happilax';
update asin set brand_id=165 where lower(left(name,9))='hangorize';
update asin set brand_id=198 where lower(left(name,14))='hamilton hills';
update asin set brand_id=39 where lower(left(name,6))='hamama';
update asin set brand_id=350 where lower(left(name,7))='hallops';
update asin set brand_id=387 where lower(left(name,6))='gymbee';
update asin set brand_id=70 where lower(left(name,4))='gym1';
update asin set brand_id=276 where lower(left(name,12))='gutter games';
update asin set brand_id=463 where lower(left(name,7))='grundig';
update asin set brand_id=120 where lower(left(name,11))='grippi ring';
update asin set brand_id=293 where lower(left(name,8))='grillman';
update asin set brand_id=335 where lower(left(name,11))='grill trade';
update asin set brand_id=130 where lower(left(name,7))='greenco';
update asin set brand_id=333 where lower(left(name,13))='gran shopping';
update asin set brand_id=78 where lower(left(name,15))='graham products';
update asin set brand_id=27 where lower(left(name,8))='grabease';
update asin set brand_id=396 where lower(left(name,9))='gourmesso';
update asin set brand_id=141 where lower(left(name,14))='gold lion gear';
update asin set brand_id=451 where lower(left(name,12))='go on the go';
update asin set brand_id=6 where lower(left(name,8))='glamlily';
update asin set brand_id=52 where lower(left(name,8))='girlzone';
update asin set brand_id=313 where lower(left(name,8))='genskins';
update asin set brand_id=95 where lower(left(name,12))='genie crafts';
update asin set brand_id=232 where lower(left(name,8))='geekdigg';
update asin set brand_id=392 where lower(left(name,7))='gateron';
update asin set brand_id=171 where lower(left(name,6))='g-rack';
update asin set brand_id=123 where lower(left(name,11))='fuxion toys';
update asin set brand_id=261 where lower(left(name,13))='fuxion sports';
update asin set brand_id=459 where lower(left(name,9))='furemover';
update asin set brand_id=89 where lower(left(name,12))='friday 7care';
update asin set brand_id=79 where lower(left(name,18))='fountain city soap';
update asin set brand_id=345 where lower(left(name,8))='flygrubs';
update asin set brand_id=222 where lower(left(name,7))='flybold';
update asin set brand_id=309 where lower(left(name,10))='flexi hose';
update asin set brand_id=483 where lower(left(name,17))='flatten the curve';
update asin set brand_id=338 where lower(left(name,17))='flathead products';
update asin set brand_id=430 where lower(left(name,7))='flamely';
update asin set brand_id=365 where lower(left(name,11))='firebuilder';
update asin set brand_id=235 where lower(left(name,6))='fidelo';
update asin set brand_id=26 where lower(left(name,8))='fauxreal';
update asin set brand_id=16 where lower(left(name,9))='faux real';
update asin set brand_id=496 where lower(left(name,13))='farmlyn creek';
update asin set brand_id=453 where lower(left(name,15))='farmhouse honey';
update asin set brand_id=495 where lower(left(name,14))='faithful finds';
update asin set brand_id=368 where lower(left(name,17))='fairytale wedding';
update asin set brand_id=34 where lower(left(name,7))='eyebloc';
update asin set brand_id=51 where lower(left(name,20))='exterminators choice';
update asin set brand_id=124 where lower(left(name,9))='evolution';
update asin set brand_id=103 where lower(left(name,7))='everloc';
update asin set brand_id=11 where lower(left(name,22))='evergreen pet supplies';
update asin set brand_id=162 where lower(left(name,13))='even naturals';
update asin set brand_id=133 where lower(left(name,6))='estilo';
update asin set brand_id=494 where lower(left(name,9))='epiqueone';
update asin set brand_id=125 where lower(left(name,6))='enovoe';
update asin set brand_id=307 where lower(left(name,10))='enno vatti';
update asin set brand_id=317 where lower(left(name,17))='effekt manufaktur';
update asin set brand_id=378 where lower(left(name,4))='edou';
update asin set brand_id=414 where lower(left(name,8))='edelhand';
update asin set brand_id=484 where lower(left(name,3))='eda';
update asin set brand_id=42 where lower(left(name,13))='eco amenities';
update asin set brand_id=266 where lower(left(name,5))='ebung';
update asin set brand_id=264 where lower(left(name,5))='eberg';
update asin set brand_id=210 where lower(left(name,8))='eberbart';
update asin set brand_id=425 where lower(left(name,15))='ebe emmasbyemma';
update asin set brand_id=385 where lower(left(name,10))='easy gleam';
update asin set brand_id=431 where lower(left(name,10))='east creek';
update asin set brand_id=278 where lower(left(name,12))='dynamic gear';
update asin set brand_id=269 where lower(left(name,7))='dylonic';
update asin set brand_id=324 where lower(left(name,6))='durgod';
update asin set brand_id=297 where lower(left(name,8))='duracare';
update asin set brand_id=354 where lower(left(name,9))='dreamship';
update asin set brand_id=342 where lower(left(name,11))='dr. wellthy';
update asin set brand_id=107 where lower(left(name,7))='dorence';
update asin set brand_id=366 where lower(left(name,13))='doradreamdeko';
update asin set brand_id=254 where lower(left(name,8))='donbolso';
update asin set brand_id=68 where lower(left(name,11))='dodo babies';
update asin set brand_id=69 where lower(left(name,9))='diy gifts';
update asin set brand_id=62 where lower(left(name,8))='dew well';
update asin set brand_id=492 where lower(left(name,7))='de-bird';
update asin set brand_id=193 where lower(left(name,5))='ddoxx';
update asin set brand_id=384 where lower(left(name,7))='dazmers';
update asin set brand_id=100 where lower(left(name,13))='dawhud direct';
update asin set brand_id=493 where lower(left(name,12))='curious chef';
update asin set brand_id=157 where lower(left(name,8))='cucisina';
update asin set brand_id=233 where lower(left(name,9))='crown led';
update asin set brand_id=45 where lower(left(name,9))='crenstone';
update asin set brand_id=35 where lower(left(name,11))='creative qt';
update asin set brand_id=114 where lower(left(name,14))='crave naturals';
update asin set brand_id=197 where lower(left(name,9))='craftopia';
update asin set brand_id=32 where lower(left(name,7))='cozyway';
update asin set brand_id=36 where lower(left(name,12))='country silk';
update asin set brand_id=20 where lower(left(name,19))='cottage creek farms';
update asin set brand_id=149 where lower(left(name,15))='comfy clothiers';
update asin set brand_id=72 where lower(left(name,10))='cobble pro';
update asin set brand_id=433 where lower(left(name,9))='cloudspot';
update asin set brand_id=136 where lower(left(name,13))='click n'' play';
update asin set brand_id=75 where lower(left(name,16))='clever creations';
update asin set brand_id=77 where lower(left(name,11))='clever chef';
update asin set brand_id=201 where lower(left(name,6))='cinch!';
update asin set brand_id=251 where lower(left(name,18))='childlike behavior';
update asin set brand_id=294 where lower(left(name,13))='charles daily';
update asin set brand_id=286 where lower(left(name,10))='casingwise';
update asin set brand_id=182 where lower(left(name,10))='care touch';
update asin set brand_id=265 where lower(left(name,10))='care check';
update asin set brand_id=249 where lower(left(name,10))='cali white';
update asin set brand_id=47 where lower(left(name,15))='butterfly craze';
update asin set brand_id=405 where lower(left(name,9))='burgstein';
update asin set brand_id=394 where lower(left(name,12))='buntes brett';
update asin set brand_id=131 where lower(left(name,8))='bullwork';
update asin set brand_id=491 where lower(left(name,16))='built industrial';
update asin set brand_id=352 where lower(left(name,8))='build me';
update asin set brand_id=490 where lower(left(name,5))='bryte';
update asin set brand_id=163 where lower(left(name,9))='brynnberg';
update asin set brand_id=40 where lower(left(name,11))='brush dance';
update asin set brand_id=147 where lower(left(name,8))='bruntmor';
update asin set brand_id=355 where lower(left(name,11))='brite crown';
update asin set brand_id=217 where lower(left(name,19))='brilliant evolution';
update asin set brand_id=4 where lower(left(name,16))='bright creations';
update asin set brand_id=74 where lower(left(name,15))='brew your bucha';
update asin set brand_id=191 where lower(left(name,13))='boulder tools';
update asin set brand_id=312 where lower(left(name,7))='botabee';
update asin set brand_id=409 where lower(left(name,11))='booty wipes';
update asin set brand_id=471 where lower(left(name,22))='bootiful carving tools';
update asin set brand_id=288 where lower(left(name,7))='bonorum';
update asin set brand_id=224 where lower(left(name,12))='bolt dropper';
update asin set brand_id=230 where lower(left(name,9))='body mate';
update asin set brand_id=241 where lower(left(name,11))='board geeks';
update asin set brand_id=205 where lower(left(name,5))='bnext';
update asin set brand_id=2 where lower(left(name,10))='blue panda';
update asin set brand_id=185 where lower(left(name,11))='black rhino';
update asin set brand_id=159 where lower(left(name,12))='bird blinder';
update asin set brand_id=188 where lower(left(name,13))='bins & things';
update asin set brand_id=277 where lower(left(name,13))='bigtime signs';
update asin set brand_id=448 where lower(left(name,15))='bigtime designs';
update asin set brand_id=204 where lower(left(name,15))='big red rooster';
update asin set brand_id=118 where lower(left(name,7))='bestway';
update asin set brand_id=489 where lower(left(name,20))='best paper greetings';
update asin set brand_id=337 where lower(left(name,9))='bellmietz';
update asin set brand_id=142 where lower(left(name,10))='bellanails';
update asin set brand_id=281 where lower(left(name,12))='bella & balu';
update asin set brand_id=427 where lower(left(name,8))='beeleeve';
update asin set brand_id=325 where lower(left(name,11))='beautyworks';
update asin set brand_id=236 where lower(left(name,24))='beast cooler accessories';
update asin set brand_id=310 where lower(left(name,7))='beartop';
update asin set brand_id=37 where lower(left(name,10))='bearington';
update asin set brand_id=164 where lower(left(name,6))='beachr';
update asin set brand_id=441 where lower(left(name,4))='baäb';
update asin set brand_id=152 where lower(left(name,7))='barvivo';
update asin set brand_id=208 where lower(left(name,9))='barrakuda';
update asin set brand_id=435 where lower(left(name,26))='barkmaster bbq accessories';
update asin set brand_id=247 where lower(left(name,11))='banana bike';
update asin set brand_id=280 where lower(left(name,6))='bamodi';
update asin set brand_id=275 where lower(left(name,5))='bamgo';
update asin set brand_id=363 where lower(left(name,6))='balder';
update asin set brand_id=195 where lower(left(name,8))='bahidora';
update asin set brand_id=250 where lower(left(name,8))='babyleaf';
update asin set brand_id=480 where lower(left(name,29))='baby merlin''s magic sleepsuit';
update asin set brand_id=158 where lower(left(name,5))='azmed';
update asin set brand_id=252 where lower(left(name,21))='aya''s cutlery kingdom';
update asin set brand_id=209 where lower(left(name,15))='aviano hardware';
update asin set brand_id=268 where lower(left(name,6))='aviano';
update asin set brand_id=300 where lower(left(name,7))='auxesia';
update asin set brand_id=298 where lower(left(name,11))='aulett home';
update asin set brand_id=140 where lower(left(name,6))='attrac';
update asin set brand_id=488 where lower(left(name,9))='artellius';
update asin set brand_id=295 where lower(left(name,8))='armogear';
update asin set brand_id=121 where lower(left(name,12))='argan deluxe';
update asin set brand_id=91 where lower(left(name,7))='aqulius';
update asin set brand_id=38 where lower(left(name,7))='aquapaw';
update asin set brand_id=259 where lower(left(name,10))='amped & co';
update asin set brand_id=194 where lower(left(name,5))='amazy';
update asin set brand_id=332 where lower(left(name,13))='alpine choice';
update asin set brand_id=113 where lower(left(name,8))='all ride';
update asin set brand_id=102 where lower(left(name,8))='aleratec';
update asin set brand_id=374 where lower(left(name,8))='agreenie';
update asin set brand_id=112 where lower(left(name,6))='adidas';
update asin set brand_id=67 where lower(left(name,14))='ad rescue wear';
update asin set brand_id=48 where lower(left(name,7))='aculief';
update asin set brand_id=29 where lower(left(name,10))='activ life';
update asin set brand_id=383 where lower(left(name,12))='actif sports';
update asin set brand_id=438 where lower(left(name,6))='acoway';
update asin set brand_id=457 where lower(left(name,6))='acotop';
update asin set brand_id=331 where lower(left(name,8))='accutire';
update asin set brand_id=166 where lower(left(name,6))='abflex';
update asin set brand_id=192 where lower(left(name,9))='abco tech';
update asin set brand_id=454 where lower(left(name,8))='a.i.& e.';
update asin set brand_id=50 where lower(left(name,6))='a team';
update asin set brand_id=403 where lower(left(name,6))='3 bros';
update asin set brand_id=138 where lower(left(name,5))='2wayz';
update asin set brand_id=173 where lower(left(name,11))='2 lb. depot';
update asin set brand_id=515 where lower(left(name,8))='magifire';
update asin set brand_id=515 where lower(left(title,8))='magifire';